// Copyright 2017 Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED.

package adapter

import (
	"istio.io/istio/mixer/adapter/bypass"
	"istio.io/istio/mixer/adapter/circonus"
	"istio.io/istio/mixer/adapter/cloudwatch"
	"istio.io/istio/mixer/adapter/denier"
	"istio.io/istio/mixer/adapter/dogstatsd"
	"istio.io/istio/mixer/adapter/fluentd"
	"istio.io/istio/mixer/adapter/kubernetesenv"
	"istio.io/istio/mixer/adapter/list"
	"istio.io/istio/mixer/adapter/memquota"
	"istio.io/istio/mixer/adapter/noop"
	"istio.io/istio/mixer/adapter/opa"
	"istio.io/istio/mixer/adapter/prometheus"
	"istio.io/istio/mixer/adapter/rbac"
	"istio.io/istio/mixer/adapter/redisquota"
	"istio.io/istio/mixer/adapter/servicecontrol"
	"istio.io/istio/mixer/adapter/signalfx"
	"istio.io/istio/mixer/adapter/solarwinds"
	"istio.io/istio/mixer/adapter/stackdriver"
	"istio.io/istio/mixer/adapter/statsd"
	"istio.io/istio/mixer/adapter/stdio"
	adptr "istio.io/istio/mixer/pkg/adapter"
	"istio.io/istio/mixer/adapter/authz"
)

// Inventory returns the inventory of all available adapters.
func Inventory() []adptr.InfoFn {
	return []adptr.InfoFn{
		authz.GetInfo,
		bypass.GetInfo,
		circonus.GetInfo,
		cloudwatch.GetInfo,
		denier.GetInfo,
		dogstatsd.GetInfo,
		fluentd.GetInfo,
		kubernetesenv.GetInfo,
		list.GetInfo,
		memquota.GetInfo,
		noop.GetInfo,
		opa.GetInfo,
		prometheus.GetInfo,
		rbac.GetInfo,
		redisquota.GetInfo,
		servicecontrol.GetInfo,
		signalfx.GetInfo,
		solarwinds.GetInfo,
		stackdriver.GetInfo,
		statsd.GetInfo,
		stdio.GetInfo,
	}
}
